version: "3"
services:

  rocket_chat:
    image: rocket.chat:0.74.3
    environment:
      - MONGO_URL=mongodb://rc_mongo_db/mydb
    ports:
     - "3000:3000"
    networks:
     - rcdb
     - webchat
    depends_on:
     - rc_mongo_db

  rc_mongo_db:
    image: mongo:3.0
    networks:
      - rcdb
    volumes:
     - rcdb:/data/db
    command: --smallfiles

networks:
  rcdb:
  webchat:

volumes:
  rcdb:
